=== yahykader/XML-DTD-XSD-XSL/test-3-FACTURE/facture.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- New XSD document created with EditiX XML Editor (http://www.editix.com) at Mon Jan 20 12:41:10 CET 2020 -->

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

<xsd:element name="operateur">
 <xsd:complexType>
     <xsd:sequence>
        <xsd:element name="client" type="TypeClient" maxOccurs="unbouned"></xsd:element>
     </xsd:sequence>
 </xsd:complexType>
</xsd:element>

<xsd:complexType name="TypeClient">

  <xsd:sequence>

    <xsd:element name="abonnement" type="TypeAbonnement" maxOccurs="unbouned"></xsd:element>

  </xsd:sequence>

  <xsd:attribute name="code" type="xsd:int" use="required"></xsd:attribute>

  <xsd:attribute name="nom" type="xsd:string" use="required"></xsd:attribute>

</xsd:complexType>

<xsd:complexType name="TypeAbonnement">

  <xsd:sequence>

   <xsd:element name="facture" type="TypeFacture"></xsd:element>  

  </xsd:sequence>

  <xsd:attribute name="numAb" type="xsd:int" use="required"></xsd:attribute>
  <xsd:attribute name="typeAb" default="GMS">
    <xsd:simpleType>
     <xsd:restriction base="xsd:string">
      <xsd:enumeration value="GMS"></xsd:enumeration>
      <xsd:enumeration value="FIXE"></xsd:enumeration>
     </xsd:restriction>
    </xsd:simpleType>
  </xsd:attribute>
  <xsd:attribute name="dateAb" type="xsd:date" use="required"></xsd:attribute>

</xsd:complexType> 

<xsd:complexType name="TypeFacture">

   <xsd:attribute name="numFact" type="xsd:int" use="required"></xsd:attribute>

   <xsd:attribute name="dateFact" type="xsd:date" use="required"></xsd:attribute>
	<xsd:attribute name="montant" type="xsd:int" use="required"></xsd:attribute>
	<xsd:attribute name="regle" default="NON" use="required">
	 <xsd:simpleType>
         <xsd:restriction base="xsd:string">
            <xsd:enumeration value="OUI"></xsd:enumeration>
            <xsd:enumeration value="NON"></xsd:enumeration>
         </xsd:restriction>	 
 	 </xsd:simpleType>
	</xsd:attribute>

</xsd:complexType>    
</xsd:schema>

=== yahykader/XML-DTD-XSD-XSL/test-3-FACTURE/facture-xsd.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- New XML document created with EditiX XML Editor (http://www.editix.com) at Mon Jan 20 13:06:20 CET 2020 -->

<?xml-stylesheet type="text/xsl" href="facture-xsl.xsl"?>
<operateur xsi:noNamespaceSchemaLocation="D:\TravauxTest\XML\test-3-FACTURE\facture.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<client code="11" nom="ABDELKDER">
		<abonnement numAb="111" dateAb="2019-10-10" typeAb="GMS">
			<facture numFact="1111" dateFact="2019-11-11" montant="147" regle="OUI"/>
            <facture numFact="1112" dateFact="2019-11-11" montant="148" regle="OUI"/>
            <facture numFact="1113" dateFact="2019-11-11" montant="149" regle="OUI"/>
		</abonnement>
		<abonnement numAb="133" dateAb="2019-10-10" typeAb="FIXE">
			<facture numFact="1111" dateFact="2019-11-11" montant="147" regle="OUI"/>
            <facture numFact="1112" dateFact="2019-11-11" montant="148" regle="OUI"/>
            <facture numFact="1113" dateFact="2019-11-11" montant="149" regle="NON"/>
		</abonnement>
	</client>
	<client code="12" nom="YACINE">
		<abonnement numAb="555" dateAb="2019-10-10" typeAb="FIXE">
			<facture numFact="1111" dateFact="2018-11-11" montant="147" regle="OUI"/>
            <facture numFact="1112" dateFact="2018-11-11" montant="148" regle="NON"/>
            <facture numFact="1113" dateFact="2018-11-11" montant="149" regle="OUI"/>
		</abonnement>
		<abonnement numAb="666" dateAb="2019-10-10" typeAb="GMS">
			<facture numFact="1111" dateFact="2018-11-11" montant="147" regle="OUI"/>
            <facture numFact="1112" dateFact="2018-11-11" montant="148" regle="NON"/>
            <facture numFact="1113" dateFact="2018-11-11" montant="149" regle="OUI"/>
		</abonnement>
	</client>
</operateur>
